baseURL = 'https://news.hippius.com/'
languageCode = 'en-us'
title = 'HIPPIUS NEWS'
theme = "mainroad"

[Params]
  description = "DECENTRALIZED STORAGE ON BITTENSOR WITH ENCRYPTION AND ERASURE CODING"
  copyright = "The Nerve Lab "
  mainSections = ["posts"]
  customCSS = ["css/custom.css"]
  sidebarPosition = "right"
  highlightColor = "#3366FF"

[Params.logo]
  image = "/images/Logo_Box.png"
  title = "HIPPIUS NEWS"
  subtitle = "DECENTRALIZED STORAGE ON BITTENSOR"

[Params.style.vars]
  highlightColor = "#3366FF"

[Params.sidebar]
  home = true
  single = true
  list = true
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets.recent]
  title = "Recent Posts"
  length = 5

[Params.widgets.categories]
  title = "Categories"
  counter = true

[Params.widgets.tags]
  title = "Tags"
  counter = true

[build]
  writeStats = true
